### ISSUE TITLE
Out of bound error in discreteFourierTransform.c

### ISSUE THREAD

**Issue by TyeolRik** [greendow/A-variant-of-NIST-SP-800-22-test-suit#1]
Hello, I am reading the article, NIST SP800-22 Revision 1a.

I think there was an error in **official** document and source code in NIST homepage and trying to figure out.
**AND ALSO in this repository**.

```c
X = (double *)calloc(bitArrayLen, sizeof(double))  //  Line 33.

// Line 63 ~ 68
m[0] = sqrt(X[0] * X[0]);    /* COMPUTE MAGNITUDE */
for ( i = 0; i < (bitArrayLen / 2); i++ )
{
		m[i + 1] = sqrt(pow(X[2 * i + 1], (double)(2.0)) + pow(X[2 * i + 2], (double)(2.0)));
}
```

At ```X[2 * i + 2]```, this for loop will cause unexpected behavior.

For example,
Let ```bitArrayLen = 10```, then maximum value of i will be 4
then, ```2 * i + 2 = 2 * 4 + 2 = 10```. But the range of X is [0, 9]. So, this means out of bound.

How can I fix that?

* I know that this code is copied from NIST homepage. But, I am trying to figure out how to fix.
* I cannot get correct answer of 2.6.8 Example. it gave me ```N1 = 48``` not 46
* I already post this on [stackoverflow](https://stackoverflow.com/q/67695365/7105963) but no-one answer me :(

**Comment by greendow** [comment]
TyeolRik:
    Thank you for pointing out the mistake in the code of discreteFourierTransform.c ! The code segment was brougth from NIST published codes and was slightly modified. So the mistake of access violation of array elements in inherited. I think the code may be modified as follows:

line 35:     ((m = (double *)calloc((bitArrayLen / 2 + 1), sizeof(double))) == NULL) )

=>
	        ((m = (double *)calloc(((bitArrayLen - 1) / 2 + 1), sizeof(double))) == NULL) )

line 65-68:  	for ( i = 0; i < (bitArrayLen / 2); i++ )
	               {
		            m[i + 1] = sqrt(pow(X[2 * i + 1], (double)(2.0)) + pow(X[2 * i + 2], (double)(2.0)));
	                }

=>
                if ( bitArrayLen % 2 == 0)
                {
                   for ( i = 0; i < ((bitArrayLen - 2) / 2); i++ )
	           {
		        m[i + 1] = sqrt(pow(X[2 * i + 1], (double)(2.0)) + pow(X[2 * i + 2], (double)(2.0)));
	           }
                }
                else
                {
                    for ( i = 0; i < ((bitArrayLen - 1) / 2); i++ )
	            {
		         m[i + 1] = sqrt(pow(X[2 * i + 1], (double)(2.0)) + pow(X[2 * i + 2], (double)(2.0)));
	            }
                }

line 71:  	for ( i = 0; i < (bitArrayLen / 2); i++ )

=>
                for ( i = 0; i < ((bitArrayLen - 1) / 2 + 1); i++ )
    I  tried the modified program and did not find access violation of array elements any more.
    I verified the example in chapter 2.6.8 of NIST 800-22 Rev 1a. I got the same result as yours, that is, N1 = 48. I think you are right !
